### ISSUE TITLE
JUnit tests don't fail in Gradle

### ISSUE THREAD

**Issue by VoidNugget** [vert-x3/vertx-unit#18]
I'm trying to run vertx JUnit tests in Gradle, like this one
```
@RunWith(VertxUnitRunner.class)
public class MainVerticleTests {

    @ClassRule
    public static RunTestOnContext rule = new RunTestOnContext();

    static HttpServerOptions opts = MasterVerticle.getHttpServerOptions();
    static String id = "";

    static Vertx vertx;

    @BeforeClass
    public static void setupVerticle(TestContext ctx) {
        ctx.assertNotNull(opts);
        vertx = rule.vertx();
        vertx.deployVerticle(MasterVerticle.class.getName(),
            ctx.asyncAssertSuccess(res -> id = res));
    }

    @Test
    public void testSessionCookiePresent(TestContext ctx) {
        rule.vertx().createHttpClient()
            .get(opts.getPort(), "localhost", "/", res -> {
                ctx.assertEquals(res.statusCode(), 404);
            }).exceptionHandler(e -> {
            ctx.fail(e);
        }).end();
    }

    @AfterClass
    public static void tearDownVerticle(TestContext ctx) {
        if (!id.isEmpty()) {
            vertx.undeploy(id, ctx.asyncAssertSuccess(res -> {
                vertx.close();
            }));
        }
    }
}
```
It does not fail at all - just reporting exceptions to console, which misleads the ```gradle``` test reporter and producing wrong reports. Am I missing something and there should be some kind of reporter configured ? I've thought it should be done automatically in VertxUnitRunner.

**Comment by vietj** [comment]
yes it should fail, give that Vert.x Unit reports errors to Junit with its API. Thanks for reporting it I will investigate.

**Comment by vietj** [comment]
can you provide a simple Gradle project that reproduces this error ?

**Comment by VoidNugget** [comment]
[Test project](https://www.dropbox.com/s/30varvjeedhwd4p/testproj.zip?dl=0)
Well, I've found my error, I should use async objects everytime I have to assert something async'ly.

Instread of 
```
  @Test
    public void testSessionCookiePresent(TestContext ctx) {
        rule.vertx().createHttpClient()
            .get(opts.getPort(), "localhost", "/", res -> {
                ctx.assertEquals(res.statusCode(), 404);
            }).exceptionHandler(e -> {
            ctx.fail(e);
        }).end();
    }
```

I have to use async
```
  @Test
    public void testSessionCookiePresent(TestContext ctx) {
        Async async = ctx.async();
        rule.vertx().createHttpClient()
            .get(opts.getPort(), "localhost", "/", res -> {
                ctx.assertEquals(res.statusCode(), 404);
                async.complete();
            }).exceptionHandler(e -> {
            ctx.fail(e);
            async.complete();
        }).end();
    }
```
'cause assertions do not get executed at all.

It looks ugly, but it works...
I think this should be documented properly.
@vietj thanks for your attention.

**Comment by VoidNugget** [comment]
And yet I don't understand why people haven't implemented some kind of async ```handler```'s for web testing. And what the purpose of storing all those asserts in ```TestContext``` if they do not control async context ?

**Comment by vietj** [comment]
The purpose of TestContext is that the error is reported to the current test, for instance if you do:

```
public void test(TestContext ctx) {
   long now = System.currentMillis();
   vertx.setTimer(10, id -> {
      assertTrue(System.currentMillis() - now >= 10);
   }
}
```

The failure would not be reported at all, since the `setTimer` callback will throw an AssertionError that Vert.x will simply log. However doing `ctx.assertTrue(expr)` will report the error.

When a method is executed, there is no way for Vert.x Unit to know wether or not your test is done and the `Async` object is a kind of reference counting to determine this.

**Comment by vietj** [comment]
Can you tell more precisely what is missing in the documentation, so we can add it with examples

**Comment by vietj** [comment]
Perhaps also we can add some helpers for Vert.x Web that work well with Vert.x Unit

**Comment by VoidNugget** [comment]
@vietj yup, I get the point of reporting via ```TestContext``` asserts already.
I've though that adding few examples of ```TestContext.async()``` usage with JUnit async testing into docs would be nice. Because It wasn't so obvious to me.

So we've already got```TestContext.asyncAssertSuccess()``` and ```TestContext.asyncAssertFailure()```, I think that it would be nice to add ```TestContext.asyncHandler(Hander<T> whatever)``` that would wrap up handlers into ```TestContext.async() -> Async.complete() ``` calls.
