### ISSUE TITLE
asyncAssertSuccess in Groovy ?

### ISSUE THREAD

**Issue by aesteve** [vert-x3/vertx-unit#26]
Hi Julien,

Dealing with `VertxUnitRunner.groovy` atm, it works neat but I'm missing a feature I liked from  `TestContext` (the java one) : `context.asyncAssertSuccess()`.

Is it possible to add asyncSuccess, asyncFailure in Groovy ? Is the code from `TestContext.groovy` automatically generated ?

**Comment by vietj** [comment]
no it is not possible at the moment because it returns an Handler<AsyncResult> and that is forbidden by codegen.

**Comment by aesteve** [comment]
OK, no problem.

In case anyone needs it : https://gist.github.com/aesteve/4042bf1d9960e883bd92 should do the trick, even if I didn't fully test it yet.

Thanks Julien.

**Comment by vietj** [comment]
I hope we can improve codegen to handle such case in the future though.

**Comment by vietj** [comment]
actually you could contribute this meta class to Vert.x Unit I think if you declare it with extension provider like I did in Vertx Rx-Groovy.

**Comment by aesteve** [comment]
Note (for myself) for further improvements : add the metaclass, like [here](https://github.com/vert-x3/vertx-rx/blob/master/rx-groovy/src/main/resources/META-INF/services/org.codehaus.groovy.runtime.ExtensionModule)

**Comment by cescoffier** [comment]
Could we close this issue, or is there work intended to be done ?

**Comment by aesteve** [comment]
I did it in the "enhanced" groovy sugar stuff. If you use Groovy Extension modules in codegen in the future don't hesitate either to ping me or copy/paste [this](https://github.com/aesteve/vertx-groovy-sugar/blob/master/src/main/groovy/com/github/aesteve/vertx/groovy/TestContextExtension.groovy#L14-L46)
