### ISSUE TITLE
config() doesn't work during JUnit tests

### ISSUE THREAD

**Issue by davidaparicio** [vert-x3/vertx-unit#38]
Hi!

I followed the tutorial http://vertx.io/blog/unit-and-integration-tests
After than, I plugged a MongoDB (and put the IP address and ports on the JSON file). But it looks like he does not read the configuration file.. 
I tried with DargLine="-conf config.json" but without success..

**Comment by cescoffier** [comment]
Is it integration tests or unit tests ?

For unit test, it does not read the config.json file, the configuration is provided manually (hard-coded in the @Before method)

**Comment by davidaparicio** [comment]
It's for the unit tests.
Okay, the unique way to do this, it is with a parser, hard-coded in the @Before ? 

```
Gson gson = new Gson();
String jsonString = new String();

// Read the configuration file
try {
    JsonElement json = gson.fromJson(new FileReader("src/main/resources/config.json"), JsonElement.class);
    jsonString = gson.toJson(json);
} catch (FileNotFoundException e) {
    System.err.println("FileNotFoundException ||"+e.toString());
} catch (IOException e){
    System.err.println("IOException ||"+e.toString());
}
```

I looked for a solution more closed to the fat-jar system, with the -conf option.
Maybe it's a good idea to propose to surcharge the function 'config()' with 'config(String file)'? (to maybe more user-friendly)

**Comment by cescoffier** [comment]
Hi,

It’s not the unique way, you can easily read a json file and build a JsonObject.
For instance, you can use the RunCommand#getConfiguration() (https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java#L405 <https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java#L405>) method.

Clement

**Comment by davidaparicio** [comment]
Okay, thank you a lot for these comments

**Comment by skeletorkun** [comment]
as of 2018, is this still the case? it s sad that we have to hardcode the config or its path..

**Comment by tsegismont** [comment]
Yes. If you want to build a JSON object from a config file:

```java
JsonObject conf = new JsonObject(vertx.fileSystem().readFileBlocking())
```
