### ISSUE TITLE
Add Junit Jupiter (JUnit 5) support 

### ISSUE THREAD

**Issue by luolong** [vert-x3/vertx-unit#43]
JUnit 5 is right around the corner and it adds much nicer and more natural extension API.

Going forward, I hope, Vert.x will adopt this API instead of getting stuck in the legacy JUnit 4 support...

**Comment by vietj** [comment]
I believe that for junit 5 we should have a new project called `vertx-junit5` that provides only support for junit 5 that only supports junit 5 (no polyglot)   whereas the existing `vertx-unit` continues to support junit 4 and the other polyglot unit testing features.

perhaps it's worth talking on the vertx-dev list.

**Comment by luolong** [comment]
Perhaps. I started at one point implementing such a functionality, but there's a lot of internal complexity involved, so I had to abandon that project for now.

( I need to take some time to understand what exactly is going on under the covers there before I can contribute anything)

**Comment by blandger** [comment]
see #281

**Comment by jponge** [comment]
Worked started here https://github.com/jponge/vertx-junit5

**Comment by dadoonet** [comment]
@jponge Any news of your JUnit5 integration?

**Comment by vietj** [comment]
it's been integrated in stack and will be released in 3.5.1, for now you shall be able to consume it as a SNAPSHOT from Sonatype OSS repository

**Comment by dadoonet** [comment]
Great @vietj! What is the classname to use? `VertxUnitRunner` is for JUnit4. Is it available within another artifact or this one?

**Comment by jponge** [comment]
David, it's a brand new module called vertx-junit5

**Comment by dadoonet** [comment]
Yeah. I searched for it under this organization name but did not find it. Still under your name I guess?

**Comment by jponge** [comment]
No it's part of the vert-x3 org

**Comment by dadoonet** [comment]
OMG! I'm not good at using search engines ! https://github.com/vert-x3/vertx-junit5

I'm better at building them. 😉
