### ISSUE TITLE
Surefire Parallel Unit Test Execution

### ISSUE THREAD

**Issue by vjkoskela** [vert-x3/vertx-unit#45]
We have a project with mixed set unit tests where some are vanilla JUnit tests and others are vertx-unit tests annotated with `@RunWith(VertxUnitRunner.class)`. Our Surefire plugin is configured for parallel execution:

```
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.19.1</version>
              <configuration>
                <parallel>methods</parallel>
                <threadCount>4</threadCount>
                <perCoreThreadCount>true</perCoreThreadCount>
              </configuration>
        </plugin>
```

However, this seems to conflict with vertx-unit as we get random test failures in those tests. I can certainly see how that can happen given the nature of Vert.x but the tests declare their own instance of `Vertx` in `@Before` so it was somewhat surprising that they were not isolated from concurrent execution.

If serial execution is required I would ask that it be added to the documentation, otherwise if this is not supposed to happen I can see about creating a small example that exhibits this behavior.

**Comment by vietj** [comment]
@vjkoskela I don't think there should be an issue, can you investigate what is going on ?

**Comment by vjkoskela** [comment]
Sorry, I didn't get a chance to look into this. Unfortunately, I've changed employers and am no longer working Vert.x (at least for the time being). Keep up the great work and feel free to close this issue.
