### ISSUE TITLE
Cannot call Async.complete several times

### ISSUE THREAD

**Issue by DMien** [vert-x3/vertx-unit#46]
Hello,

I just discover Vertx, so maybe i'm wrong, but in a Junit Test If i write 

`Async async = context.async(2);`

I expect to call async.complete 2 times before it really complete. But instead i got a `java.lang.IllegalStateException: The Async complete method has been called more than 2 times, check your test.`

I'm using Vertx 3.4.0-SNAPSHOT and first line of `AsyncImpl.complete is int value = current.getAndSet(0);` so the counter value equals 0 at the end of method call, then i can't call the `complete`method anymore

As i said i'm new to vertx so maybe i'm missing or misunderstood something.

Thanks for your help, and thanks for this great project

**Comment by alexlehm** [comment]
Looks like this is bug, can you please create an example showing the issue so that Julien can fix it?

**Comment by DMien** [comment]
`Vertx vertx = Vertx.vertx();

        TestSuite suite = TestSuite.create("the_test_suite");

        suite.test("my_test_case", context -> {
            Async async = context.async(2);
            EventBus eb = vertx.eventBus();

            eb.consumer("ping", event -> {
                System.out.println(event.body());
                context.assertEquals("ping", event.body());
                event.reply("pong");
                async.complete();
            });
            eb.send("ping", "ping", event -> {
                System.out.println(event.result().body());
                context.assertEquals("pong", event.result().body());
                async.complete();
            });
        }).run(vertx);`

Hope it's help

**Comment by vietj** [comment]
actually the number works with `countDown()` and not `complete()`

**Comment by DMien** [comment]
Yes, works like a charm, `countDown()` decrement counter and when reached 0 complete the Async. 

Maybe the Javadoc and exception's message of `complete()` shall be updated, but again, it works !

Thanks Julien

**Comment by vietj** [comment]
what would you suggest as different wording ?

**Comment by iamwwc** [comment]
@vietj 

I am not a native English speaker, I cannot understand complete docs

It said

```
The test case will complete when all the async objects have their Async.complete() method called at least once
```

For example

```
Async async = ctx.async(2);
```

For a single async object, we call countdown twice , so this object complete

But why we need complete method?

Did complete used when we want to complete async object directly without call many time countdown?

**Comment by vietj** [comment]
so to clarify, if you have async(n), you need to call countdown n times or complete one, perhaps the doc should be corrected
