### ISSUE TITLE
The Async complete method has been called more than 1 times

### ISSUE THREAD

**Issue by chefhoobajoob** [vert-x3/vertx-unit#49]
I think this is a bug. Shouldn't this construct complete successfully with 3.4.1?

```java
Async submit = theContext.async( 9 );
for ( int i = 0; i < 9; i++ ) {
    client.submitJob( submission, theContext.asyncAssertSuccess( job -> {
        submit.countdown();
    } ) );
}
submit.await();
```

Instead, I'm finding that this only completes successfully when the call to `theContext.async()` is given an argument of 1, and the loop control condition is changed to execute only once.

If the loop is changed to execute more than once, and `async` is called with a matching number, the test always fails on the last time through the loop with the `async complete...has been called more than 1 times` error.

If I change the loop construct to this:

```java
for ( int i = 0; i < 9; i++ ) {
	Async submit = theContext.async();
	client.submitJob( submission, theContext.asyncAssertSuccess( job -> {
		submit.complete();
	} ) );
	submit.await();
}
```

...the test always passes. Is this behavior expected? If so, why?

**Comment by vietj** [comment]
I believe the test should pass in both cases, it looks like a bug

**Comment by vietj** [comment]
in the thread executing the test on the event loop ?

**Comment by vietj** [comment]
I've added this to JUnitTest in the test suite of Vert.x Unit and it passes:

```
  public static class TestBug {

    Vertx vertx;

    @Before
    public void before() {
      vertx = Vertx.vertx();
    }

    @After
    public void after() {
      vertx.close();
    }

    @Test
    public void testMethod(TestContext context) {
      Async submit = context.async(9);
      for (int i = 0; i < 9; i++) {
        vertx.setTimer(10, id -> {
          submit.countDown();
        });
      }
      submit.await();
    }
  }

  @Test
  public void testBug() {
    Result result = run(TestBug.class);
    assertEquals(1, result.getRunCount());
    assertEquals(0, result.getFailureCount());
  }
```

**Comment by alexlehm** [comment]
I added a few logs to your test and created a skeleton class to provide the client method and it looks like the tests works as expected. Could you please check if something is called more than once if you test class?

https://gist.github.com/alexlehm/a9970fe66edfd381b399b91fddf0ccad

**Comment by chefhoobajoob** [comment]
@vietj - forgot to mention: no, the test isn't running on the event loop.

I have these setup methods:

```java
    Vertx vertx;

    @Before
    public void before(TestContext context) {
        vertx = Vertx.vertx();
    }

    @After
    public void after(TestContext context) {
        vertx.close( context.asyncAssertSuccess() );
    }
```

...and then inside the test method where I'm seeing this problem, there is one successful `asyncAssertSuccess` call for deploying the verticle-under-test before the loop. The whole thing looks like so:

```java
    @Test(timeout = 3000L)
    public void returnsRequestedJobs( TestContext theContext ) throws Exception {
        Async deploy = theContext.async();
        vertx.deployVerticle( "service:" + getServiceId(),
                theContext.asyncAssertSuccess( deploymentID -> {
                    deploy.complete();
                }));
        deploy.await();

        SoftwareEntity submitter = new SoftwareEntity()
                .setName( getClass().getName() )
                .setVersion( "1.0.0" )
                .setHost( VertxHost.hostName() );

        JsonObject data = new JsonObject()
                .put( "wanker", new JsonObject()
                        .put( "boofer", "barfy" )
                        .put( "poopy", 14 ) )
                .put( "tod", System.currentTimeMillis() );

        SubmitJobOptions submission = new SubmitJobOptions()
                .setSubmitter( submitter )
                .setType( "test" )
                .setData( data );

        Client client = Client.create( vertx );

        List<Job> jobs = new ArrayList<>();
        Async submit = theContext.async();
        for ( int i = 0; i < 9; i++ ) {
            client.submitJob( submission, theContext.asyncAssertSuccess( job -> {
                jobs.add(job);
                submit.complete();
            } ) );
        }
        submit.await();
}
```

**Comment by chefhoobajoob** [comment]
I'll see if I can get the same results as @alexlehm using a mock verticle similar to his skeleton and update with findings. If there's anything suspicious you see in the above code, please advise.

**Comment by chefhoobajoob** [comment]
With a mock reproducer, I get the same results as @alexlehm.  I'm at a loss to explain the behavior I'm seeing in the project I'm working on. I don't see how anything in the client or verticle code under test could have any influence on the async test behavior. Any troubleshooting suggestions?

I created a gist that most closely resembles the implementation under test - and it passes without error.

https://gist.github.com/chefhoobajoob/7977709318657c9af7f5f91008fc7c6c

**Comment by chefhoobajoob** [comment]
The only other thing I can think of that is different between the reproducer and the CUT is that the actual client implementation is using the rx-ified vertx api so that instead of issuing `eventBus send` requests with handlers, it's using `rxSend`, so there are some delegates wrapping various calls in there.

I'll try updating the reproducer client to use the rx-ified vertx and see what happens.

**Comment by chefhoobajoob** [comment]
Ok - so changing the `TestClient` in the gist had no effect - it still passes. The last remaining difference I can think of is that the actual client implementation is produced by vertx codegen, with essentially the same underlying implementation (the rx-ified version) as in the gist, but I'm at a loss to explain how any of that could be causing this problem.

I think I'm going to give up troubleshooting for the time being and just go with the working loop construct.

I don't suppose it will help, but below is the call stack that `vertx-unit` reports when the error occurs:

```
java.lang.IllegalStateException: The Async complete method has been called more than 1 times, check your test.

	at io.vertx.ext.unit.impl.TestContextImpl$Step$AsyncImpl.complete(TestContextImpl.java:164)
	at io.vertx.ext.unit.impl.TestContextImpl.lambda$asyncAssertSuccess$1(TestContextImpl.java:386)
	at org.github.chefhoobajoob.ClientBase$RequestImpl.lambda$send$2(ClientBase.java:143)
	at rx.Single$11.onSuccess(Single.java:1791)
	at rx.internal.util.ScalarSynchronousSingle$1.call(ScalarSynchronousSingle.java:36)
	at rx.internal.util.ScalarSynchronousSingle$1.call(ScalarSynchronousSingle.java:32)
	at rx.Single.subscribe(Single.java:1967)
	at rx.Single$2$1.onSuccess(Single.java:670)
	at rx.Single$2$1.onSuccess(Single.java:666)
	at rx.internal.operators.SingleOnSubscribeMap$MapSubscriber.onSuccess(SingleOnSubscribeMap.java:74)
	at rx.internal.operators.SingleOnSubscribeMap$MapSubscriber.onSuccess(SingleOnSubscribeMap.java:74)
	at rx.internal.operators.SingleDoOnEvent$SingleDoOnEventSubscriber.onSuccess(SingleDoOnEvent.java:63)
	at io.vertx.rx.java.SingleOnSubscribeAdapter.lambda$call$0(SingleOnSubscribeAdapter.java:31)
	at io.vertx.rxjava.core.eventbus.EventBus$2.handle(EventBus.java:155)
	at io.vertx.rxjava.core.eventbus.EventBus$2.handle(EventBus.java:152)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$convertHandler$1(EventBusImpl.java:334)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:505)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by alexlehm** [comment]
What stikes me as strange is that the count is 1 which could point to the asyncAssertSuccess method instead of the Async created with count 9.
Could you maybe try to replace the asyncAssertSuccess method from TestContext with a local copy of the method and add a log to check if this async is completed more than once. If that is the case, the reason may be somewhere else in the code

**Comment by chefhoobajoob** [comment]
@alexlehm - yes, I agree. I'll experiment some more with this taking your suggestions and update. Thanks for the pointer...

**Comment by chefhoobajoob** [comment]
Great. I finished out the rest of the test cases for this project, fixed some bugs in the library being tested, then went back to this test case to try your suggestions, and the above code that previously was failing with that async error is now no longer failing.

So, looks like there's nothing to investigate. Thank you both @vietj and @alexlehm for your feedback. Sorry for the distraction!
