### ISSUE TITLE
If an exception occurs, the test does not fail, but hangs

### ISSUE THREAD

**Issue by aesteve** [vert-x3/vertx-unit#52]
Here's a simple reproducer : https://github.com/aesteve/vertx-unit-hangs

Simply run the test and you'll see.

iirc we discussed a while ago about the fact that if an exception occurred within the test, it wasn't failing the test, which could indeed be an issue. But here it's even more difficult to tell what's happening.

The second test `simplyThrow` is here to help debugging, but I'm most annoyed by the first test `httpBodyHandler` which is a typical use case.

If you're expecting the http body to be a JsonObject and it's not, this is a major regression you want to catch without having to wait for `async` to timeout.

Let me know if I can help you.

**Comment by bhowell2** [comment]
@aesteve I've noticed this as well. 

Here's my reproducer that's a bit different than yours: https://github.com/bhowell2/VertxUnitHangingReproducer
(I should have searched before even starting to create it, but I had already creating a simple test to confirm my suspected issue) 

Vertx-dev dicussion as well: https://groups.google.com/forum/#!topic/vertx-dev/MIbRe4HSK-8

I'll take a look at fixing this issue in a bit.

**Comment by bhowell2** [comment]
@aesteve there is somewhat a fix to this. i've posted it on the vertx-dev discussion. essentially you need to register an exception handler for vertx -- you can do this in the `@Before` method of your tests and call `testContext.fail(err)` with whatever value is returned. vertx-unit uses the same `TestContext` for `@Before` and test methods, so this will fail the test as desired and keep it from hanging. Obviously this could be a problem in the future if vertx-unit does not use the same context (not sure why that would change) or if you overwrite `vertx.exceptionHandler` sometime after the `@Before` has registered it.

**Comment by aesteve** [comment]
Thanks for the pointer !

**Comment by vietj** [comment]
@bhowell2 a test for the same `TestContext` can be added in this project I think

**Comment by bhowell2** [comment]
@vietj i just checked and there actually is already a test that does this, so this should avoid any regression issues. I think this can be closed, but maybe in the docs this should be mentioned a bit more? I could create a pull request to add a bit more info for it if desired. Let me know.

**Comment by jotak** [comment]
Hi,
I have something quite similar, with a test hanging on failure, here is a minimal example: https://gist.github.com/jotak/3779cb4a8fc9a23cfdafd970cc386214

I would expect that on failure, all created "async" objects would be completed.

**Comment by vietj** [comment]
I think we can close this issue. Can you open another issue for your case @jotak ?

**Comment by jotak** [comment]
yes: #58
