### ISSUE TITLE
Allow to use in combination with other assertion frameworks

### ISSUE THREAD

**Issue by jotak** [vert-x3/vertx-unit#54]
It would be nice to use VertxUnit in combination with other assertion frameworks, such as _assertj_.

As I understand, it essentially means that async "completeness" must be handled on assertion errors.

So I suggest to add a method in `TestContext` such as `void run(Runnable r)` that takes any piece of code (which may contain assertions using another assertion framework), catches AssertionError and use the TestContext fail method.

**Comment by jotak** [comment]
PS: I'm writing a PR

**Comment by vietj** [comment]
can you take inspiration from vertx-junit 5 that provides a new verify method on VertxTestContext ? it would be good to have the same API in both project.

**Comment by jotak** [comment]
Indeed it looks exactly the same as what I'm writing, expect the method name, so I'll call it `verify` as well.

**Comment by jotak** [comment]
@vietj , `Runnable` is not allowed? It's used in the junit5 module, but in vertx-unit I get:
```
[ERROR] diagnostic: /work/vertx-unit/src/main/java/io/vertx/ext/unit/TestContext.java:212: error: Could not generate model for io.vertx.ext.unit.TestContext#verify(java.lang.Runnable): type java.lang.Runnable is not legal for use for a parameter in code generation
  TestContext verify(Runnable block);
```

**Comment by jotak** [comment]
(I could use Handler<Void> , but it would have an unused parameter)

**Comment by vietj** [comment]
Handler<Void> is the polyglot way to go

**Comment by vietj** [comment]
so it's fine
