### ISSUE TITLE
Failed async should not block when the test is failed

### ISSUE THREAD

**Issue by jotak** [vert-x3/vertx-unit#58]
I reproduced this issue in a minimal test:
https://gist.github.com/jotak/3779cb4a8fc9a23cfdafd970cc386214

As you can see I have to surround my assertions in `try/finally` in order to get the async completed upon failure. Another workaround would be to set a timeout ( `async.await(5000)` ), but still I would expect the test to fail immediately on assertion failure.

I haven't checked the internals of `TestContext`, but I would expect all created `Async` objects to be completed automatically on failure.

**Comment by vietj** [comment]
any taker for 3.5.1 ? can we check the same for vertx-junit5 ? cc @jponge

**Comment by jponge** [comment]
Quick reply on `vertx-junit5`: the test context completion always has a
timeout.

**Comment by bhowell2** [comment]
The event loop is being blocked when calling `await`, since the test are being run with VertxUnitRunner`. As for why the `try/finally` block is cancelling the tests i'd have to look into a bit more. Is this still something that needs to be fixed? I.e., should you be able to call `await` when running on the `VertxUnitRunner`?

**Comment by bhowell2** [comment]
Sorry, just assumed that he was using RunTestOnContext when I saw the `VertxUnitRunner`, i see that he is not. Looking into this now to see what's up.

**Comment by jotak** [comment]
@bhowell2 really? Btw I'm on 3.5.1-SNAPSHOT
I've just rebased vertx-unit from master and rebuilt locally. It's still hanging here.

**Comment by bhowell2** [comment]
@jotak I see now! For what it's worth, it was fine on 3.2.1! (I had manually typed in the dependency for vertx-unit, a long time ago and didnt realize that all my other vertx packages were 3.5.0+ and unit was still on 3.2.0.) I've gone back to test all the releases and it fails on 3.3.0-3.5+.

**Comment by vietj** [comment]
can you provide a patch ?

**Comment by bhowell2** [comment]
@vietj Yeah, I'll get one to you by tomorrow.

**Comment by bhowell2** [comment]
@vietj I believe I have a simple fix, if it is a valid assumption that no other code in the test method should be run after TestContext#fail() is called. 

If this is the case, there were two test cases that I think were incorrectly implemented. 

The two cases in question: 

```java
// TestSuiteNoEventLoopTest.java
  public void testEndsAfterCallback() throws Exception {
    AtomicBoolean ok = new AtomicBoolean();
    AtomicBoolean after = new AtomicBoolean();
    TestSuite suite = TestSuite.create("my_suite").
        test("my_test", context -> {
          try {
            context.fail();
          } catch (AssertionError e) {
          }
         // should not be run once fail is called?
          if (!after.get()) {
            ok.set(true);
          }
        }).after(context -> {
      after.set(true);
    });
    TestReporter reporter = new TestReporter();
    run(suite, reporter);
    reporter.await();
    assertTrue(ok.get());    // note, i do not think OK should be true here? It should be after.get().

  // TestSuiteTestBase
  public void runTestWithFailBeforeAsync() throws Exception {
    AtomicReference<AssertionError> failure = new AtomicReference<>();
    BlockingQueue<Async> queue = new ArrayBlockingQueue<>(1);
    TestSuite suite = TestSuite.create("my_suite").
        test("my_test", context -> {
          try {
            context.fail();
          } catch (AssertionError e) {
            failure.set(e);
          }
          // again, should not be run once failure is called?
          queue.add(context.async());
        });
    TestReporter reporter = new TestReporter();
    run(suite, reporter);
    reporter.await();
    // These will then be removed.
    Async async = queue.poll(2, TimeUnit.SECONDS);
    async.complete();

``` 

I'm submitting a pull request with the aforementioned changes.
