### ISSUE TITLE
Provide a GroovyUnitRunner

### ISSUE THREAD

**Issue by aesteve** [vert-x3/vertx-unit#6]
For now, if we use :

```java
@RunWith(VertxUnitRunner.class)
```

then in our methods : 

```java
@Test
public void testSomething(TestContext context) {
}
```

TestContext is the Java Testcontext implementation, not the Groovy one.

Maybe we could have a `VertxGroovyUnitRunner.class` which injects the `GroovyTestContext`

**Comment by bytor99999** [comment]
Hmm, isn't this already done?

I have

import io.vertx.groovy.ext.unit.TestContext

That looks like a groovy version to me. Or am I missing something.

**Comment by aesteve** [comment]
I haven't rechecked lately (I will), but last time I checked there was a io.vertx.groovy.ext.unit.TestContext indeed but the one injected in the method at runtime when using `@RunWith(VertxUnitRunner.class)` was the java one, not the groovy one. Resulting in an error : "Your method should have no parameter or an instance of io.vertx.unit.TestContext"

I'll check again tomorrow.

**Comment by aesteve** [comment]
Thanks a lot Julien.

**Comment by vietj** [comment]
would you mind to give a try quickly ?

**Comment by aesteve** [comment]
It works !

Such a pleasure to see all these little bars green again !

**Comment by bytor99999** [comment]
Cool. Yeah green bars are better to see than little green men.
