### ISSUE TITLE
Async.countDown

### ISSUE THREAD

**Issue by magh** [vert-x3/vertx-unit#60]
Using vertx unit 3.5.0

Would be nice to get an exception if async.countDown is called more than context.async(X) times.

Below code fails when uncommenting the commented out code but returns success if left commented out. Uncommented test is fixed with context.async(2).
```
import rx.Observable;

@RunWith(VertxUnitRunner.class)
public class ObservableTest {
    @Test(timeout = 5000)
    public void test(final TestContext context) {
        final Async async = context.async(1); //2
        Observable.just(1).subscribe(next -> {
            context.assertEquals(1, next);
            // context.assertNotEquals(0, async.count());
            async.countDown();
        }, error -> {
            context.fail(error);
        }, () -> {
            // context.assertNotEquals(0, async.count());
            async.countDown();
        });
    }
}
```

**Comment by tsegismont** [comment]
@magh this is expected. This behavior is consistent with `java.util.concurrent.CountDownLatch#countDown`.

**Comment by jponge** [comment]
BTW `vertx-junit5` provides such a behavior with checkpoints, that can be made strict and thus throw an exception when flagged more than need be.

**Comment by vietj** [comment]
how about using instead countDownStrict() method rather than adding an async boolean ?

**Comment by tsegismont** [comment]
Because when you create your Async object it's time to think about why
counting should be strict or not.

Mixing countdown and countdownStrict calls on the same Async method sounds
suspicious.

**Comment by jponge** [comment]
I concur with Thomas.

On Thu, Jan 25, 2018 at 11:24 AM, Thomas Segismont <notifications@github.com

**Comment by vietj** [comment]
so it should rather be called strictAsync, I'm not in favor of an overload with a boolean.

**Comment by jponge** [comment]
Isn't what Thomas already did?

**Comment by tsegismont** [comment]
You may be looking at the wrong PR (I had mistakenly opened it against my
own fork). The new one is does not expose an overloaded method to the user.
