### ISSUE TITLE
Please add assertThat to TestContext

### ISSUE THREAD

**Issue by alexlehm** [vert-x3/vertx-unit#8]
I changed all assertions in my project to use testContext.assert.., currently VertxTestBase has assertThat, but vertx-unit doesn't.

it would be great if you could add that (probably not for 3.0)

**Comment by jebbench** [comment]
The ability to use Hamcrest marchers would be great - especially using the Hamcrest-JSON matches for testing REST services.

**Comment by cescoffier** [comment]
I will soon publish a blog post on this subject explaining how you can use Harmcrest with vertx-unit. It just requires a 5 line class ;-).

**Comment by cescoffier** [comment]
@jebbench @alexlehm 

Check https://gist.github.com/cescoffier/5cbf4c69aa094ac9b1a6
If you use these `assertThat` methods, you can use any Hamcrest matchers with vert.x unit.

**Comment by cescoffier** [comment]
I've written a blog post about this: http://vertx.io/blog/using-hamcrest-matchers-with-vert-x-unit/

We could consider adding the `VertxMatcherAssert` class in vert.x unit (as it does not require any new dependency (hamcrest core is included in junit).

I let @vietj choose.

**Comment by vietj** [comment]
I would like in 3.3 to have a hook in Vert.x context to be able to use any AssertionError that would make TestContext almost useless (except maybe for creating Async), so I would rather wait for that if it can become real (and allow to use JUnit ecocystem) first.

**Comment by cescoffier** [comment]
Makes lots of sense.

**Comment by aschrijver** [comment]
@vietj Could you explain a bit more on the hook mechanism?
I read in the 3.3.0 release notes that we can now use AssertJ and Hamcrest, both of whom I'd like to integrate.
Is there some code, an example or documentation that you can point out?

**Comment by vietj** [comment]
Hi,

here are the examples:

- https://github.com/vert-x3/vertx-examples/blob/master/unit-examples/src/test/java/io/vertx/example/unit/test/JUnitAndHamcrestTest.java
- https://github.com/vert-x3/vertx-examples/blob/master/unit-examples/src/test/java/io/vertx/example/unit/test/JUnitAndAssertJTest.java

**Comment by cescoffier** [comment]
I guess we can close this issue. `assertThat` is not required anymore as with the _global_ exception handler we can use any assertion library (Hamcrest, AssertJ, Rest Assured...).

@vietj WDYT ?

**Comment by vietj** [comment]
👍

**Comment by aschrijver** [comment]
@vietj , @cescoffier : Thanks for the info!
