### ISSUE TITLE
Asserts have reversed parameter order compared to Junit

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-unit#9]
WIth Junit asserts, the expected is the first param, the actual the second. With vertx-unit it is the other way around.

This is going to be confusing for people coming from JUnit.

**Comment by cescoffier** [comment]
We should probably also look at assertj (http://joel-costigliola.github.io/assertj/). 

Assertj is an (extensible) assertion library heavily used and making writing test a bit simpler and in a more readable way. So, in addition to junit assertions, we may want to provide `assertThat` _sentences_.

**Comment by vietj** [comment]
this order exists because of codegen that will not accept String first as it creates dispatch ambiguities.
